defaults:
  - blank_ratio: 25-75
  - dataset: '012'
  - model: attention
  - settings: config
  - _self_

hydra:
  job:
    chdir: true
  sweep:
    subdir: ${hydra.job.override_dirname}

path: model_weights.pth
use_cuda: true
seed: 0
lr: 0.0001
reg: 0.0001